name: Deploy Site on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Cloudflare Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Send Deploy Hook
        run: curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}"
